#+TITLE: Matt Rogers' Emacs Config
#+OPTIONS: toc:4 h:4
#+STARTUP: showeverything

* Configuration
** About
   :PROPERTIES:
   :CUSTOM_ID: babel-init
   :END:
<<babel-init>>
My little emacs configuration. This is inspired by DOOM, Spacemacs, and Sacha
Chua's emacs config. It's an attempt to make my emacs configuration less of a
mess.

Run =M-x org-babel-tangle= (=C-c C-v t=) to get a =mattr.el= file and then
symlink that to =init.el=

** Faster startup tweaks

Now, let's get some startup optimizations in place. Like reducing garbage collection at startup
#+BEGIN_SRC emacs-lisp :tangle yes
(setq gc-cons-threshold 128000000)
(add-hook 'after-init-hook #'(lambda ()
			       ;; restore after startup
			       (setq gc-cons-threshold 800000)))
#+END_SRC
** Package initialization
#+BEGIN_SRC emacs-lisp :tangle yes
;; All the package set up goes here
(require 'package)

(setq package-enable-at-startup nil)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; Set up use-package
(eval-when-compile (require 'use-package))
(require 'bind-key)

(setq use-package-verbose t)
(setq use-package-always-ensure t)
(setq load-prefer-newer t)
#+END_SRC

Don't let byte compiled packages get out of sync
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package auto-compile
  :defer t
  :config (auto-compile-on-load-mode))

#+END_SRC


** Personal Information
#+BEGIN_SRC emacs-lisp :tangle yes
(setq user-full-name  "Matt Rogers"
      user-mail-address "codemattr@gmail.com")
#+END_SRC

** Setup Emacs Defaults
*** UI Chrome
I'm not a big fan of the chrome that Emacs comes with by default, so this
strips it all out. No toolbars, menu bars, scroll bars, nothing.
#+BEGIN_SRC emacs-lisp :tangle yes
(when (and (fboundp 'tool-bar-mode) (not (eq tool-bar-mode -1)))
  (tool-bar-mode -1))
(when (and (fboundp 'menu-bar-mode) (not (eq menu-bar-mode -1)))
  (menu-bar-mode -1))
(when (and (fboundp 'scroll-bar-mode) (not (eq scroll-bar-mode -1)))
  (scroll-bar-mode -1))
;; tooltips in echo-aera
(when (and (fboundp 'tooltip-mode) (not (eq tooltip-mode -1)))
  (tooltip-mode -1))
#+END_SRC


Let's customize the message in the scratch buffer and not show the startup screen.
#+BEGIN_SRC emacs-lisp :tangle yes
(setq inhibit-startup-screen t
      initial-scratch-message ";; ready\n\n")
#+END_SRC

I'm lazy, so typing 'yes' and 'no' is right out
#+BEGIN_SRC emacs-lisp :tangle yes
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Line numbers and column numbers in the status bar please
#+BEGIN_SRC emacs-lisp :tangle yes
(setq line-number-mode t)
(setq column-number-mode t)
#+END_SRC

I don't like double spaced sentences even though I know it's the "correct" thing to do
#+BEGIN_SRC emacs-lisp :tangle yes
(setq sentence-end-double-space nil)
#+END_SRC

These are a few more defaults I haven't decided whether or not I want to keep
from my old config yet.

;; Set the default line wrap to 78
(set-default 'fill-column 78)

;; Highlight parenthesis after you type/navigate over them
(show-paren-mode t)

;; Don't wrap long lines
(setq-default truncate-lines nil)

;; Only use spaces
(setq-default indent-tabs-mode nil)

*** Backups
I've not been a big fan of backups really but I think I'll break my normal
rule and give them a try but at least keep them confined to a single directory
rather than scattered all over my file system. Backups and auto save files go into ~backups~
and ~auto-save-list~ directories respectively under my ~emacs.d~.

#+BEGIN_SRC emacs-lisp :tangle yes
(setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
(setq delete-old-versions -1)
(setq version-control t)
(setq vc-make-backup-files t)
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
#+END_SRC

*** Keybindings
**** Leader key mappings
Set up a base leader key map to use to map the rest of the keys to. It
will be used frequently throughout the rest of the file
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package bind-map)

(bind-map my-normal-base-leader-map
  :keys ("M-m")
  :evil-keys (",")
  :evil-states (normal))
#+END_SRC

*** Whitespace
Show empty lines, trailing whitespace, and tabs
#+BEGIN_SRC emacs-lisp :tangle yes
(setq whitespace-style '(face empty trailing tab-mark))
#+END_SRC
Enable whitespace detection for text modes and prog modes
#+BEGIN_SRC emacs-lisp :tangle yes
(add-hook 'prog-mode-hook 'whitespace-mode)
#+END_SRC
Please don't clutter my mode line

Trigger whitespace cleanup whenever I want
#+BEGIN_SRC emacs-lisp :tangle yes
(bind-map-set-keys my-normal-base-leader-map
  "sw" 'whitespace-cleanup)
#+END_SRC

*** Editor Config Support
Support =.editorconfig=
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package editorconfig
  :defer t
  :init
  (progn
    (with-eval-after-load 'editorconfig
      (diminish 'editorconfig-mode)))
  :config
  (progn
    (editorconfig-mode 1)))
#+END_SRC

** Evil Mode Setup
I've trained myself to think in vim, so evil mode is a necessity for
me. And the more like vim we can make emacs, the better

#+BEGIN_SRC emacs-lisp :tangle yes
(use-package evil
  :demand t
  :init
  (setq evil-want-C-u-scroll t
	evil-want-visual-char-semi-exclusive t
	evil-want-Y-yank-to-eol t
	evil-magic t
	evil-echo-state t
	evil-indent-convert-tabs t
	evil-ex-search-vim-style-regexp t
	evil-ex-substitute-global t
	evil-ex-visual-char-range t  ; column range for ex commands
	evil-insert-skip-empty-lines t
	evil-mode-line-format 'nil
	;; more vim-like behavior
	evil-symbol-word-search t
	;; don't activate mark on shift-click
	shift-select-mode nil)
  :config
  ;; Move to new split -- setting `evil-split-window-below' &
  ;; `evil-vsplit-window-right' to non-nil mimics this, but that doesn't update
  ;; window history. That means when you delete a new split, Emacs leaves you on
  ;; the 2nd to last window on the history stack, which is jarring.
  ;; Borrowed from doom-emacs
  (defun +evil*window-follow (&rest _)  (evil-window-down 1))
  (defun +evil*window-vfollow (&rest _) (evil-window-right 1))
  (advice-add #'evil-window-split  :after #'+evil*window-follow)
  (advice-add #'evil-window-vsplit :after #'+evil*window-vfollow))


(use-package evil-surround
  :config
  (global-evil-surround-mode 1))

(use-package evil-matchit
  :config
  (global-evil-matchit-mode 1))

(use-package evil-numbers)
(use-package evil-tabs)
(evil-mode 1)
#+END_SRC


** Popup Windows!
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package popwin
  :config
  (popwin-mode 1)
  (bind-map-set-keys my-normal-base-leader-map
      "wpm" 'popwin:messages
      "wpp" 'popwin:close-popup-window))
#+END_SRC

** Version Control
I love how simple this is to setup and how well it works without a
bunch of tweaking out of the box. magit is good stuff

#+BEGIN_SRC emacs-lisp :tangle yes
(use-package magit
  :defer t
  :config
  (with-eval-after-load 'magit
    (require 'evil-magit))
  (bind-map-set-keys my-normal-base-leader-map
    "gs" 'magit-status))
(use-package evil-magit :defer t)
#+END_SRC



** Themeing
I'm still trying to decide if I'm going to stick with terminal emacs
or go with GUI emacs. Right now, I'm thinking GUI emacs will do well
enough with everything so I'm going to try that. But we need a nice
theme for it first...

Let's go with doom-themes for now
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package doom-themes
  :init
    (setq doom-themes-enable-bold t
          doom-themes-enable-italic t)
  :config
    (load-theme 'doom-one t)
    (doom-themes-visual-bell-config) ; flash mode line on error
    (doom-themes-org-config) ; improve org-mode native fontification
)
#+END_SRC
