#!/usr/bin/env bash

# Cowardly refuse to run if we're not on macOS
if [ "$(uname -s)" != "Darwin" ]
then
  echo "This is not macOS. Aborting."
  exit 1
fi

# Transitioning to nix. Let's install some shit.
# Can't say I'm a super fan of the curl | sh pattern
# but I've got enough trust in this after looking at the script.
curl -L https://nixos.org/nix/install | sh


# I'm stubbornly refusing to put a Brewfile at the root of this repo, so we're streaming one in to `brew bundle` from standard output
brew bundle --file=- <<EOF
tap "homebrew/cask"
tap "homebrew/cask-fonts"

cask "1password"
cask "1password-cli"
cask "alfred"
cask "anki"
cask "arc"
cask "bambu-studio"
cask "dash"
cask "discord"
cask "docker"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "fantastical"
cask "hammerspoon"
cask "iterm2"
cask "obs"
cask "obsidian"
cask "raycast"
cask "slack"
cask "spotify"
cask "steam"
cask "visual-studio-code"
cask "vlc"
cask "wezterm"
cask "zoom"

cask "font-iosevka"
cask "font-symbols-only-nerd-font"

brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "fzy"
brew "gh"
brew "git"
brew "gnupg"
brew "hub"
brew "jq"
brew "mr"
brew "neovim"
brew "pinentry-mac"
brew "ripgrep"
brew "tmux"
brew "zsh"
EOF
