#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

# Do some rudimentary OS detection and run the appropriate bootstrap script to install dependencies for things in my dotfiles
os=$(uname -s)
keep_going=""
if [ "$os" == "Darwin" ]
then
  ./script/bootstrap-macos && keep_going=1
else
  if [ -f /etc/debian_version ]
  then
    ./script/bootstrap-debian && keep_going=1
  else # assume ArchLinux
    ./script/bootstrap-arch && keep_going=1
  fi
fi


if [ -n "$keep_going" ]
then
  # shamelessly stolen from https://github.com/jordemort/dotfiles/blob/6643b5b0a883be5fd773bb6903e17d512b3747f8/setup.sh
  # put our dotfiles in the proper place

  homesick_repos="$HOME/.homesick/repos"
  preferred_dir="$homesick_repos/dotfiles"
  homeshick_dir="$homesick_repos/homeshick"
  current_dir=$(git rev-parse --show-toplevel)

  if [ "$current_dir" != "$preferred_dir" ] ; then
    mkdir -p "$(dirname "$preferred_dir")"
    mv "$current_dir" "$preferred_dir"
  fi

  # switch to our preferred directory
  pushd $preferred_dir &>/dev/null

  # setup homeshick
  git clone https://github.com/andsens/homeshick.git "$homeshick_dir"

  # clone zinit for zsh plugins
  git clone https://github.com/zdharma-continuum/zinit.git ~/.zinit/bin

  # clone asdf for tool management
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  cd ~/.asdf
  git checkout "$(git describe --abbrev=0 --tags)"

  # run homeshick to link the dotfiles in
  $homeshick_dir/bin/homeshick -f link dotfiles

  popd &>/dev/null
fi

