#!/usr/bin/env bash

set -eo pipefail

is_linux() { [ "$(uname -s)" = "Linux" ]; }
is_macos() { [ "$(uname -s)" = "Darwin" ]; }

is_devcontainer() {
  [ -n "${CODESPACES:-}" ] || [ -n "${REMOTE_CONTAINERS:-}" ] || [ -f /.dockerenv ]
}

script_dir="$(cd "$(dirname "$0")" && pwd)"
repo_dir="$(cd "$script_dir/.." && pwd)"

if ! command -v nix &>/dev/null; then
  LIX_INSTALL_OPTIONS="--no-confirm --enable-flakes"

  echo "==> Installing Lix"
  LIX_INSTALL_TMP=$(mktemp) || exit 1
  curl -sSf -L https://install.lix.systems/lix -o "$LIX_INSTALL_TMP"
  chmod u+x "$LIX_INSTALL_TMP"
  if is_macos; then
    LIX_INSTALL_PLATFORM="macos"
  else
    LIX_INSTALL_PLATFORM="linux"
  fi

  echo "$LIX_INSTALL_TMP" install "$LIX_INSTALL_PLATFORM" "$LIX_INSTALL_OPTIONS" | bash
fi

if is_devcontainer; then
  echo "==> Applying home manager config"
  nix run home-manager --extra-experimental-features "nix-command flakes" -- switch --flake "$repo_dir#devcontainer" --impure
elif is_macos; then

  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

  echo "==> Building the config"
  nix --extra-experimental-features "nix-command flakes" build .#darwinConfigurations.gloop.system

  echo "==> Activating the config"
  #./result/activate
fi
