#!/usr/bin/env bash

# Cowardly refuse to run if we're not on macOS
if [ "$(uname -s)" != "Darwin" ]
then
  echo "This is not macOS. Aborting."
  exit 1
fi

# I'm stubbornly refusing to put a Brewfile at the root of this repo, so we're streaming one in to `brew bundle` from standard output
brew bundle --file=- <<EOF
tap "homebrew/cask"
tap "homebrew/cask-fonts"

cask "hammerspoon"
cask "dash"
cask "visual-studio-code"
cask "docker"
cask "alfred"
cask "iterm2"
cask "obsidian"
cask "parsec"
cask "raycast"
cask "spotify"
cask "vlc"

cask "font-iosevka-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-inconsolata-nerd-font"

brew "bat"
brew "exa"
brew "fd"
brew "fzf"
brew "fzy"
brew "gh"
brew "git"
brew "gnupg"
brew "hub"
brew "jq"
brew "mr"
brew "neovim"
brew "pinentry-mac"
brew "ripgrep"
brew "tmux"
brew "zsh"
EOF
