#!/bin/bash
export NVIM_APPNAME="nvchad"

rm -rf ~/.config/$NVIM_APPNAME
rm -rf ~/.local/share/$NVIM_APPNAME
rm -rf ~/.local/state/$NVIM_APPNAME

git clone https://github.com/NvChad/starter ~/.config/$NVIM_APPNAME
rm -rf ~/.config/$NVIM_APPNAME/.git
